# Generated by Django 4.2.3 on 2023-12-25 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subject',
            name='Title',
        ),
        migrations.AddField(
            model_name='subject',
            name='title',
            field=models.CharField(default=0, max_length=64),
            preserve_default=False,
        ),
    ]
