# Generated by Django 4.2.3 on 2023-12-25 06:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_remove_subject_title_subject_title'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BioAns',
            new_name='Answer',
        ),
        migrations.RenameModel(
            old_name='BioQuest',
            new_name='Question',
        ),
    ]
