# Generated by Django 4.2.3 on 2023-12-25 06:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_year_alter_question_subject'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Subject',
            new_name='Subjects_GCE',
        ),
    ]
