# Generated by Django 4.2.3 on 2023-12-25 07:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_rename_subject_subjects_gce'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Subjects_GCE',
            new_name='Subject',
        ),
    ]
