# Generated by Django 4.2.3 on 2023-12-26 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_rename_subjects_gce_subject'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='art',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='subject',
            name='science',
            field=models.BooleanField(default=False),
        ),
    ]
