# Generated by Django 4.2.3 on 2023-12-27 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_subject_art_subject_science'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='paper',
            field=models.CharField(choices=[('Paper 1', 'Paper 1'), ('Paper 2', 'Paper 2'), ('Paper 3', 'Paper 3')], default='Paper 1', max_length=20),
        ),
    ]
