# Generated by Django 4.2.3 on 2024-01-24 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_question_paper'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='series',
            name='series_choice',
        ),
        migrations.RemoveField(
            model_name='series',
            name='user',
        ),
        migrations.AddField(
            model_name='series',
            name='title',
            field=models.CharField(default=0, max_length=64),
            preserve_default=False,
        ),
    ]
