# Generated by Django 4.2.3 on 2024-01-24 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_remove_series_series_choice_remove_series_user_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Series',
        ),
        migrations.AddField(
            model_name='subject',
            name='advanced',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='subject',
            name='ordinary',
            field=models.BooleanField(default=False),
        ),
    ]
